from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from ceresa.billing import repository
from ceresa.core.settings import HOTEL_CONFIG


router = APIRouter(prefix="/billing", tags=["Billing"])


class BillingAccountCreate(BaseModel):
    reservation_id: int = Field(..., ge=1)
    notes: str | None = Field(default=None, max_length=1000)


class BillingChargeCreate(BaseModel):
    source_module: str = Field(..., min_length=2, max_length=50)
    description: str = Field(..., min_length=2, max_length=250)
    amount_cents: int = Field(..., gt=0)


class BillingPaymentCreate(BaseModel):
    payment_method: str = Field(..., min_length=2, max_length=50)
    amount_cents: int = Field(..., gt=0)
    reference: str | None = Field(default=None, max_length=150)


def get_account_or_404(account_id: int) -> dict:
    """
    Returns one billing account or raises HTTP 404.
    """
    account = repository.get_billing_account_by_id(account_id)

    if account is None:
        raise HTTPException(
            status_code=404,
            detail="Billing account not found.",
        )

    return account


@router.get("/status")
def get_billing_status() -> dict:
    return {
        "module": "billing",
        "status": "active",
        "message": "Billing module is running",
    }


@router.post("/accounts")
def create_billing_account(
    account: BillingAccountCreate,
) -> dict:
    """
    Creates one billing account for a reservation.
    """
    if not repository.reservation_is_billable(
        account.reservation_id
    ):
        raise HTTPException(
            status_code=404,
            detail="Reservation not found or cancelled.",
        )

    try:
        account_id = repository.create_billing_account(
            reservation_id=account.reservation_id,
            notes=account.notes,
        )

    except Exception as error:
        if repository.is_unique_constraint_error(error):
            raise HTTPException(
                status_code=409,
                detail=(
                    "A billing account already exists "
                    "for this reservation."
                ),
            )

        raise

    return {
        "message": "Billing account created successfully",
        "billing_account_id": account_id,
    }


@router.get("/accounts/{account_id}")
def get_billing_account(account_id: int) -> dict:
    """
    Returns an account with its charges, payments and balance.
    """
    account = get_account_or_404(account_id)
    account["currency"] = HOTEL_CONFIG["currency"]

    return account


@router.post("/accounts/{account_id}/charges")
def add_billing_charge(
    account_id: int,
    charge: BillingChargeCreate,
) -> dict:
    """
    Adds a charge generated by a hotel module.
    """
    get_account_or_404(account_id)

    charge_data = charge.model_dump()
    charge_data["source_module"] = (
        charge_data["source_module"].strip().lower()
    )
    charge_data["description"] = (
        charge_data["description"].strip()
    )

    charge_id = repository.create_charge(
        billing_account_id=account_id,
        charge_data=charge_data,
    )

    return {
        "message": "Billing charge created successfully",
        "charge_id": charge_id,
    }


@router.post("/accounts/{account_id}/payments")
def add_billing_payment(
    account_id: int,
    payment: BillingPaymentCreate,
) -> dict:
    """
    Registers a payment made by the guest.
    """
    get_account_or_404(account_id)

    payment_data = payment.model_dump()
    payment_data["payment_method"] = (
        payment_data["payment_method"].strip().lower()
    )

    payment_id = repository.create_payment(
        billing_account_id=account_id,
        payment_data=payment_data,
    )

    return {
        "message": "Billing payment created successfully",
        "payment_id": payment_id,
    }